AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AcmCertificateArn:
    Type: String
  Environment:
    AllowedValues:
      - dev
      - prod
    Default: dev
    Type: String
  Stack:
    AllowedValues:
      - blue
      - green
    Default: green
    Type: String
  HostedZoneId:
    AllowedValues:
      - Z13FENV9QCX5IY
      - Z2JEP63TRLSULI
    Default: Z13FENV9QCX5IY
    Type: String

Resources:
  FrontEndBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub ${Stack}.${Environment}.responsetime.net
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: Allow-OAI-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/${CloudFrontOriginAccessIdentity}
            Action: s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${Stack}.${Environment}.responsetime.net/*
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${Stack}.${Environment}.responsetime.net/*

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CloudFront Origin Access Identity for responsetime's ${Environment} environment ${Stack} stack

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${Stack}.${Environment}.responsetime.net
        Comment: !Sub CloudFront Distribution for responsetime's ${Environment} environment ${Stack} stack
        CustomErrorResponses:
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 400
            ResponseCode: 400
            ResponsePagePath: /error/400.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /error/403.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error/404.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 405
            ResponseCode: 405
            ResponsePagePath: /error/405.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 414
            ResponseCode: 414
            ResponsePagePath: /error/414.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 416
            ResponseCode: 416
            ResponsePagePath: /error/416.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 500
            ResponseCode: 500
            ResponsePagePath: /error/500.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 501
            ResponseCode: 501
            ResponsePagePath: /error/501.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 502
            ResponseCode: 502
            ResponsePagePath: /error/502.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 503
            ResponseCode: 503
            ResponsePagePath: /error/503.html
          -
            ErrorCachingMinTTL: 1
            ErrorCode: 504
            ResponseCode: 504
            ResponsePagePath: /error/504.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: False
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 2592000
          MinTTL: 0
          #PathPattern: '*'
          SmoothStreaming: false
          TargetOriginId: !Sub S3-${Stack}.${Environment}.responsetime.net
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: True
        HttpVersion: http2
        IPV6Enabled: False
        Origins:
          -
            DomainName: !Sub ${Stack}.${Environment}.responsetime.net.s3.amazonaws.com
            Id: !Sub S3-${Stack}.${Environment}.responsetime.net
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  FrontEndUrl:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt [CloudFrontDistribution, DomainName]
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub ${Stack}.${Environment}.responsetime.net
      Type: A
