AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    AllowedValues:
      - dev
      - prod
    Default: dev
    Type: String
  Stack:
    AllowedValues:
      - blue
      - green
    Default: blue
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  HomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: home.lambda_handler
      CodeUri: home/
      Events:
        HomeApi:
            Type: Api
            Properties:
                Path: /home
                Method: GET

  FrontEndBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub responsetime-${Environment}-${Stack}-frontend-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled

  BackEndBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub responsetime-${Environment}-${Stack}-backend-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled

Outputs:
  HomeApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/home"
  HomeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HomeFunction.Arn
  HomeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HomeFunctionRole.Arn
