name: cfn-lint
on:
  push:
    paths:
    - "*template.yaml"

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: puppet-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "*template.yaml"
