name: deploy-dev-blue
on:
  push:
    branches:
      - deploy/dev-blue
jobs:
  responsetime-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: andyschwabe/responsetime-deploy@master
        env:
          ACCESSKEY: access
          ACMCERTIFICATEARN: blue.dev.responsetime.net
          ENVIRONMENT: dev
          REGION: us-east-2
          SECRETKEY: secret
          STACK: blue
        with:
          args: "createCreds"
