name: deploy-prod-green
on:
  push:
    branches:
      - deploy/prod-green
jobs:
  responsetime-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: andyschwabe/responsetime-deploy@master
        env:
          ACCESSKEY: ${{secrets.RTPROD_AWS_ACCESS}}
          ACMCERTIFICATEARN: prod.green.responsetime.net
          ENVIRONMENT: prod
          REGION: us-east-2
          SECRETKEY: ${{secrets.RTPROD_AWS_SECRET}}
          STACK: green
        with:
          args: "createCreds"
