name: deploy-prod-blue
on:
  push:
    branches:
      - deploy/prod-blue
jobs:
  responsetime-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: andyschwabe/responsetime-deploy@master
        env:
          ACCESSKEY: access
          ACMCERTIFICATEARN: prod.blue.responsetime.net
          ENVIRONMENT: prod
          REGION: us-east-2
          SECRETKEY: secret
          STACK: blue
        with:
          args: "createCreds"
